---
title: "Handling error messages"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Handling error messages}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`comtradeRggregator` uses [`comtradr`](https://github.com/ropensci/comtradr) to access Comtrade trade data using its [API](https://comtrade.un.org/data/doc/api/).
This means that you sometimes are confronted with a set of API related error messages. To learn more about the different types of
errors see [w3.org](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).

# Typical API error messages in `comtradeRggregator` and how to fix them

## Error code 400

Typically, you get a **400 (bad request) error** whenever any of the input parameters are specified incorrectly.

Double-check all input parameters for `download_Comtrade()` for any issues/inconsistencies.

## Error code 409

One of the most common issues is that if you hit a usage limit a
**409 (conflict) error** is returned along with a message specifying why the request was blocked and when requests may resume.

Whenever such an error occurs during one of its queries, `comtradeRggregator` pauses the data query. Next, after a specified cool-off of an hour, it tries to resume the download. This means that you can conveniently max out the user limit for bulk downloads, and  `comtradeRggregator` will ensure your query fails because of usage limits. The limits for unauthenticated requests, i.e. guests, are set to 100 requests per hour (per IP address or authenticated user). See [Comtrade's API help page](https://comtrade.un.org/data/doc/api/) for more information.

However, this is **not** practice I would wish to encourage. Instead, you should acquire an authentication code (token) which you can then use when calling `download_Comtrade()`for large bulk downloads.

1. Follow the instruction on Comtrade's API page to [Comtrade's API help page](https://comtrade.un.org/data/doc/api/) to get access to an authentication code (token).

2. You can check the validity of your token [here](https://comtrade.un.org/ws/CheckRights.aspx).

3. Use the token as input parameter `token` in function `download_Comtrade()` to get unlimited (authenticated) usage of 10,000 requests per hour.

## Error code 500

Unexplored/unspecified error. `comtradeRggregator` will pause the download for 60 seconds and re-send the last unsuccessful query again.

This should typically eliminate the issue, and your request should go through after at most a handful of attempts.

In case you are running a big request, i.e., you try to download a big chunk of data, consider increasing the interval between every single request. You can do this by increasing the parameter value for `sleep` in `download_Comtrade()`.

# Other error messages

### Error in `curl::curl_fetch_memory()`

Sometimes, especially when downloading large(r) chunks of data, you might run into the following error message:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
```

From experience, and in the context of this package, the error message relates to the file you are trying to download with `curl`. In other words, there are limits on the respective file sizes and download times per file, and one of your `download_Comtrade()` queries might hit one of those `curl` limits.
  
In such a case, try re-running your `download_Comtrade()` query by reducing the value for `ext_cnt`, which sets the number of countries extracted with each request (default and maximum is 5). The lower the number for `ext_cnt`, the fewer countries are downloaded simultaneously, hence the smaller the file size and the shorter the download time. Alternatively, the same error message also gets triggered when your device gets disconnected from the internet, so also double-check to make sure you are still online.
